[package]
name = "simple-binary-heap-tree"
version = "0.1.0"
authors = ["dzmitry-lahoda <dzmitry@lahoda.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
