on:
  pull_request:
    branches:
      - master
jobs:
  git-lfs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actionsdesk/lfs-warning@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filesizelimit: 10MB
          exclusionPatterns: |
            **/*.pnguses: actionsdesk/lfs-warning@v3.2
