% defines logic for packages installation
% app(Y) define`s chocolatey application named Y, e.g. app(nodejs.install) is equivalent to <package id="nodejs.install"/>`
% category(CATEGORY,Y) means that application Y is of some category, e.g category(virtualization,virtualbox)
% role(ROLE,Y) means that application is targeted for specific audience, e.g. role(developer,sharpdevelop) is for developers
% any application without explicit defined role is assigned role(user,Y)
% environment(ENV,Y) means that application should be installed only for specifci environemnt, e.g. developer can have host and guest VMs, or different VMs for different application tiers
% until marked otherwise, all application are for environment(any,Y)
% what about thing like DRM free Firefox 39 beta  64 bit ? so firefox pre  for some users while firefox stable for others 
% what about depenency?
% windows 8 vs 10

app(nodejs_install).
app(conemu).
app(doublcmd).
app(sharpdevelop).
app(virtualbox).
app(virtualbox_extensionpack).
app(vboxguestadditions_install).
app(wincdemu).

environment(host,virtualbox).
environment(personal,virtualbox_extensionpack).
environment(host,virtualbox_extensionpack).
environment(guest,vboxguestadditions_install).
% any should be generated for all application until specified otherwice
environment(any,sharpdevelop).

category(virtualization,virtualbox).
category(host,virtualbox_extensionpack).
category(virtualization,virtualbox_extensionpack).
category(explorer,doublecmd).
category(editor,notepadplusplus).
category(player,vlc).
category(codec,ffdshow).


role(power_user,process_hacker).
role(developer,sharpdevelop).
role(power_user,conemu).
role(developer,ilspy).
role(user,doublcmd).
role(user,vlc).
role(user,notepadplusplus).
% user role should be autogenerated for application without explicit roles 
role(user,wincdemu).


% developer guest virtual machine should not include host 
for_developer_guest_vm(Y) :- for_developer(Y); (\+ environment(host,Y)).
for_developer_host_vm(Y) :- for_developer(Y) ; (\+ environment(guest,Y)) . 

% if application is for developer then implies development category
in_category(development,Y) :- role(developer,Y); category(development,Y).

% if app for power_user then also for developer
for_developer(Y) :- for_power_user(Y); in_category(development,Y).

% if application for user then also for power_user
for_power_user(Y) :- role(power_user,Y); role(user,Y). 

for_user(Y) :- role(user,Y).

% ?- for_developer_guest_vm(virtualbox_extensionpack).
% false
% ?- for_developer_host_vm(vboxguestadditions_install).
% false
% ?- for_developer_guest_vm(vboxguestadditions_install).
% true
% ?- for_developer_host_vm(virtualbox_extensionpack)
% true
% ?- for_power_user(vlc).
% true
% ?- for_developer(vlc).
% true
% ?- for_user(conemu)
% false
% ?- for_power_user(conemu)
% true
% ?- in_category(development,sharpdevelop)
% true
% ?- for_developer(sharpdevelop)
% true
% ?- for_user(wincdemu)
% true